#!/bin/sh

if [ -f $1 ]; then
  case $1 in
    *.tar.gz)
      tar xf $1
      ;;
    *.tar)
      tar xf $1
      ;;
    *.bz2)
      bunzip2 $1
      ;;
    *.gz)
      gunzip $1
      ;;
    *.zip)
      unzip $1
      ;;
    *.Z)
      uncompress $1
      ;;
    *)
      echo "$1 cannot be extracted via extract"
      ;;
  esac
else
  echo "$1 is not a valid file"
fi
