#!/bin/sh
# Initialise a file from the template

git_init(){
  message="Init"
  [[ $# -gt 0 ]] && message=$1
  git init
  git add .
  git commit -m "$message"
  git log --oneline -1
}

html_init(){
  echo "<!doctype html>
<html>
<head>
	<meta charset='UTF-8'>
	<script type='text/javascript' src='jquery-1.8.0.min.js'></script>
	<link type='text/css' rel='stylesheet' href='reset.css'>
</head>
<body>
</body>
</html>" > $1
	cp "${DEV_LIB_HOME}/jquery-1.8.0.min.js" .
	cp "${DEV_LIB_HOME}/reset.css" .
}

shell_init(){
  echo "#!/bin/sh" > $1
  chmod +x $1
}

case $1 in
  git)
    shift
    git_init "$@"
    ;;
  html)
    shift
    html_init "$@"
    ;;
  sh|shell)
    shift
    shell_init "$@"
    ;;
  *)
    echo " Unsupported format."
    exit 1
    ;;
esac
