#!/bin/sh
# Initialise a file from the template

shell(){
  echo "#!/bin/sh" > $1
  chmod +x $1
}

html(){
  echo "<!doctype html>
<html>
<head>
	<meta charset='UTF-8'>
	<script type='text/javascript' src=''></script>
	<link type='text/css' rel='stylesheet' href=''>
</head>
<body>
</body>
</html>" > $1
}

case $1 in
  sh|shell)
    shift
    shell "$@"
    ;;
  html)
    shift
    html "$@"
    ;;
  *)
    echo " Unsupported format."
    exit 1
    ;;
esac
