#!/usr/bin/env python
import json, sys
filename =  sys.argv[1]
path = sys.argv[2]
linestring = open(filename, 'r').read()
data = json.loads(linestring)

for key in path.split('.'):
	if type(data) == list:
		data = data[int(key)]
	else:
		data = data[key]

print json.dumps(data, indent=4)
