#!/usr/bin/env bash
if [ $# -eq 0 ]; then
  echo $RANDOM
elif [ $# -eq 1 ]; then
  if echo $1 | egrep -q '^[0-9]+$'; then
    echo $((RANDOM*$1/32767))
  else
    echo "Invalid arguments: argument must be an integer"
  fi
else
  echo "Invalid arguments: argument should be no more than one."
fi
